# Generated by Django 6.0.3 on 2026-04-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["username"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
