# Generated by Django 6.0.3 on 2026-04-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sky_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["title"], "verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
    ]
