# Generated by Django 6.0.3 on 2026-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky_blog", "0002_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
